source 'https://rubygems.org'

gem 'rails', '~> 5.0.0', '>= 5.0.0.1'

<%- gems %>

group :development, :test do
  <%- testGems %>
end

group :development do
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
