# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6e54f6a296b6418dd94f560a41e537b5b47127624962091e84938a14c944e9b94c33ca94359474df63c1982b5ffd1c1da3c881bcc257031b47865091b540153

test:
  secret_key_base: bf672c333926c2b5019c166bc4dabe4c30ce455b55373daeebf88153fc50d23c038d41d4ccc3eb374e45bc128ae01b154aa9c792c5f25a55b005908b8cb1921d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%%= ENV["SECRET_KEY_BASE"] %>
